#!/bin/bash
# This script removes debug output from fw_printenv.

set -o nounset
set -o errexit
set -o pipefail

if [[ ${EUID} -ne 0 ]]; then
    echo "Error: This script must be run as root."
    exit 1
fi

/usr/bin/fw_printenv $@ | grep -vE "^Environment OK.*"
